### ISSUE TITLE
Misunderstanding or bug?

### ISSUE THREAD

**Issue by TheLazyLemur** [cferdinandi/reef#207] opened 2024-08-01 11:40 UTC
**Test case:** https://codepen.io/cferdinandi/pen/GRmOyJJ

I have this code snippet where I am trying to pass two events into a component. However the second one that is used in the template throws a error:

```js
let { signal, component, render } = reef;

customElements.define('count-up', class extends HTMLElement {
    constructor() {
        super();

        this.count = signal(0);

        let countUp = () => {
            this.count.value++;
        };

        let startDrag = () => {
            console.log('startDrag');
        };

        this.events = {
            countUp: countUp,
            startDrag: startDrag
        };

        component(this, this.template, { events: this.events });
    }

    template = () => {
        return `
            <div draggable="true" onmousedown="startDrag()">
                <button onclick="countUp()">Clicked ${this.count.value} times</button>
            </div>
            `;
    }

});
```

```
Uncaught ReferenceError: countUp is not defined
    at HTMLButtonElement.onclick ((index):1:1)
```

**Comment by cferdinandi** [comment] 2024-08-03 02:58
Definitely a bug, seemingly the same one here: https://github.com/cferdinandi/reef/issues/200

Closing this issue only because it's a duplicate of an existing bug that already has some chat around it, but linking the two as related.

Thanks for filing this!

**Closed by cferdinandi** 2024-08-03 02:58 UTC
