### ISSUE TITLE
Reef is not defined when using router

### ISSUE THREAD

**Issue by davidbrooksio** [cferdinandi/reef#69] opened 2020-10-23 09:45 UTC
Thank you for creating Reef, I'm really enjoying using it. I thought I would give the router a try and it seems I have fallen at the first hurdle.

I installed Reef using npm `npm i reefjs` and I am using webpack 5 to bundle my modules. The **only** thing that is in my index.js file is:

```
import Reef from 'reefjs';
import 'reefjs/router';
```

If I run using webpack serve then I get the following console error:

```
Uncaught ReferenceError: Reef is not defined
    at Object../node_modules/reefjs/router.js (router.js:2)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:60)
    at Module../src/index.js (main.bundle.js:18)
    at __webpack_require__ (bootstrap:21)
    at startup:4
    at startup:5
```

If I build the bundle then it's the same error but in my js bundle:

```
Uncaught ReferenceError: Reef is not defined
    at Object.469 (main.bundle.js:2)
    at n (main.bundle.js:2)
    at main.bundle.js:2
    at main.bundle.js:2
    at main.bundle.js:2
```

I really wanted to get this working and build a single page site so any help would be gratefully received :)

**Comment by cferdinandi** [comment] 2020-11-21 04:26
Sorry for the late reply here... is the path to your files correct? 

If you're using something like Rollup (my tool of choice), I typically need to update the `import` statement to point to the actual location of Reef (and the correct filename) in my filesystem. If you're using `npm` to install Reef, what you've got above should be fine.

**Comment by davidbrooksio** [comment] 2020-11-24 11:41
HI, I am using npm and webpack. I have found that if I edit `node_modules/reefjs/router.js` and include `import Reef from 'reefjs';` at the top of this file then it works but this isn't ideal because as soon as I update Reef this will be overwritten.

**Comment by cferdinandi** [comment] 2020-11-24 13:29
Can you link me to a reduced test case? Happy to do some debugging.

**Comment by davidbrooksio** [comment] 2020-11-24 16:09
Hi

I have set up a reduced test case on CodePen, however (annoyingly and predictably) everything works fine. I have added my code which is essentially your code from the docs and I have commented out my two imports in favour of the cdn imports. You can view the pen at https://codepen.io/davidbrooksio/pen/MWjgaZz?editors=1111 but to be honest it isn't going to tell you much (because everything works).

With regards to my local code, I have created a repo at https://github.com/davidbrooksio/reefsinglepage which you can clone, npm install and then `npm run start`;
Hopefully this will show the error.

**Comment by orionrush** [comment] 2020-11-25 13:55
I can confirm the test cases

Browser console:
```
Uncaught ReferenceError: Reef is not defined
    at Object../node_modules/reefjs/router.js (router.js:2)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:60)
    at Module../src/index.js (index.js:4)
    at __webpack_require__ (bootstrap:21)
    at startup:4
    at startup:5
```

On adding `reefjs` and `reef-router` as npm dependencies I've noticed this warning which might be relaviant:

```
npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

`npm build:produiction` is missing the `mini-css-extract-plugin`, however once added, this also throws a similar `Uncaught ReferenceError`, so Dev and Prod would seem to be giving the same results. 

```
Uncaught ReferenceError: Reef is not defined
    at Object../node_modules/reefjs/router.js (router.js:2)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:60)
    at Module../src/index.js (main.bundle.js:16)
    at __webpack_require__ (bootstrap:21)
    at startup:4
    at startup:4
```

I suspect this is a Webpack config issue?

**Comment by cferdinandi** [comment] 2020-11-25 14:37
Thanks for the extra details there! My lack of familiarity with webpack may be hurting me here. I tested using Rollup and everything worked as expected, but I know webpack is quite popular.

I'll see if I can get to the root of this. Thanks y'all!

**Comment by davidbrooksio** [comment] 2020-11-25 16:48
Thanks @onionrush and @cferdinandi 
Always nice to know I'm not going mad!

**Comment by tersoo** [comment] 2020-12-01 16:15
I had the same issue and solved it by extracting the router into a library on npm `reefjs-browser-router`.

Have resorted to installing reefjs and the library and everything works just fine in that instance. It would be nice to see this resolved.

**Comment by shockdevv** [comment] 2021-01-10 01:11
I have the same problem, but I'm using https://parceljs.org/.

**Comment by cferdinandi** [comment] 2021-01-31 22:12
I owe y'all an update, and I'm sorry!

I believe I've isolated the problem to ReefRouter using `Reef` internally. In non-NPM imports, that's generally not an issue since Reef is in the global or lexical scope. When using certain bundlers (like Webkit or ParcelJS), Reef is assigned to a different variable, and the methods the Router relies on can't be found.

This is why you're seeing the `Reef not defined` message.

This is going to require me to make some updates [similar to what Vue has done with their `Vue.use()` plugin system](https://router.vuejs.org/installation.html#npm). I'll keep you posted, but at the very least, I know why it's happening.

**Comment by cferdinandi** [comment] 2021-02-03 04:09
This should be fixed with v8.x, but it does require an extra step when working with module bundlers.

When used with a module system, you must explicitly associate Reef with the router with the `ReefRouter.install()` method.

```js
import Reef from 'https://cdn.jsdelivr.net/npm/reefjs/dist/reef.es.min.js';
import ReefRouter from 'https://cdn.jsdelivr.net/npm/reefjs/dist/router.es.min.js';

ReefRouter.install(Reef);
```

Also, please note that the naming convention has changed from `Reef.Router()` to `ReefRouter()`.

**Closed by cferdinandi** 2021-02-03 04:09 UTC
Labels: bug
