### ISSUE TITLE
Router: Redirect Upon Entry

### ISSUE THREAD

**Issue by tooolbox** [cferdinandi/reef#54] opened 2020-05-24 06:08 UTC
As of 7.3.0 it seems that the redirect functionality of the router doesn't work for an entry point.  I.e. if I want to redirect `/` to `/blah/` upon first visit then nothing occurs.

Seems like [that particular feature is disabled](https://github.com/cferdinandi/reef/blob/master/dist/router.js#L181) in favor of [only redirecting on route change](https://github.com/cferdinandi/reef/blob/master/dist/router.js#L276).

I figure you are already aware of this, but just putting in a plug 😃 

P.S. Very nice project!

**Comment by cferdinandi** [comment] 2020-05-24 13:12
Duplicate of https://github.com/cferdinandi/reef/issues/52

**Comment by tooolbox** [comment] 2020-05-24 19:09
Sorry, I don't think this is a duplicate.  Probably my fault for not providing a sample, as the issue template requested.  😨 

Let's take this set of routes:
```js
var router = new Reef.Router({
	routes: [
		{
			url: '/',
			redirect: '/dashboard/'
		},
		{
			id: 'dashboard',
			title: 'Dashboard',
			url: '/dashboard/'
		}
	],
});
```

I would think from that setup that doing an initial visit to `/` would cause a redirect to `/dashboard/` but it doesn't, because redirects are only checked when the framework detects a navigation, rather than when the page is first loaded and the route determined.  At least, that's what I see in the code that I linked to.

**Comment by cferdinandi** [comment] 2020-05-25 18:46
Ah yep, there seems to be an issue with the `/` path

**Comment by cferdinandi** [comment] 2021-02-03 04:07
This should be fixed with v8.x

**Closed by cferdinandi** 2021-02-03 04:07 UTC
Labels: bug
